NumPy(넘파이)는 'Numerical Python'의 줄임말로,
파이썬에서 대규모 다차원 배열과 행렬 연산을 쉽고 빠르게 처리할 수 있도록
도와주는 필수적인 라이브러리입니다.
🚀 특히 데이터 과학, 머신러닝, 공학 계산 분야에서 핵심적인 역할을 합니다.



 NumPy를 왜 사용할까요?

파이썬의 기본 리스트(list)도 데이터를 담을 수 있지만,
수치 계산, 특히 대용량 데이터 처리에서는 속도가 느립니다.

1
NumPy는 내부적으로 C언어로 구현되어 있어 엄청나게 빠른 연산 속도를 자랑하며,
적은 메모리로 데이터를 관리할 수 있습니다.

2. 핵심은 ndarray

NumPy의 가장 중요한 핵심은 **ndarray (N-dimensional array)**라는
다차원 배열 객체입니다. 이 ndarray는 다음과 같은 특징이 있습니다.

동일한 자료형:
배열의 모든 요소는 같은 자료형(예: 정수, 실수)이어야 합니다.
이 덕분에 메모리를 효율적으로 사용하고 연산 속도를 높일 수 있습니다.

빠른 연산:
배열 전체에 대해 반복문 없이
한 번에 연산(벡터화 연산)을 수행할 수 있어
코드가 간결해지고 속도가 매우 빠릅니다.

다양한 차원: 1차원(벡터), 2차원(행렬), 3차원 이상의 배열도 쉽게 만들 수 있습니다.

NumPy를 사용하려면 먼저 라이브러리를 설치하고 불러와야 합니다.
pip install numpy

numpy는 관례적으로 np라는 별칭으로 불러옵니다.
import numpy as np

In [3]:
## 간단한 사용 예시
# 1. NumPy 배열 생성
# 파이썬 리스트를 np.array() 함수에 전달하여 NumPy 배열을 만듭니다.
# 1차원 배열 생성
import numpy as np

my_list = [1, 2, 3, 4, 5] # 일반리스트
print(f"my_list 타입: {type(my_list)}")
arr1d = np.array(my_list) # 일반리스트 -> 넘파이 형식의 배열로 변환.
print(f"arr1d 타입: {type(arr1d)}")

print("1차원 배열:")
print(arr1d)

# 2차원 배열 (행렬) 생성
my_list2d = [[1, 2, 3],
             [4, 5, 6]]
print(f"my_list2d 타입: {type(my_list2d)}")
arr2d = np.array(my_list2d)# 일반리스트 -> 넘파이 형식의 배열로 변환.
print(f"arr2d 타입: {type(arr2d)}")

print("\n2차원 배열:")
print(arr2d)

# 배열 정보 확인.
# shape, ndim, dtype 등의 속성으로 배열의 정보를 확인할 수 있습니다.
print(f"배열의 모양 (shape): {arr2d.shape}") # (행, 열)
print(f"배열의 차원 (ndim): {arr2d.ndim}")
print(f"배열 요소의 자료형 (dtype): {arr2d.dtype}")

my_list 타입: <class 'list'>
arr1d 타입: <class 'numpy.ndarray'>
1차원 배열:
[1 2 3 4 5]
my_list2d 타입: <class 'list'>
arr2d 타입: <class 'numpy.ndarray'>

2차원 배열:
[[1 2 3]
 [4 5 6]]
배열의 모양 (shape): (2, 3)
배열의 차원 (ndim): 2
배열 요소의 자료형 (dtype): int64
